const genre = [
  "Action and Adventure",
  "Classics",
  "Graphic Novel",
  "Detective and Mystery",
  "Fantasy",
  "Historical Fiction",
  "Horror",
  "Thriller",
  "Literary Fiction",
  "Romance",
  "Science Fiction",
  "Short Stories",
  "Suspense and Thrillers",
  "Women's Fiction",
  "Biography",
  "Cookbooks",
  "Essays",
  "History",
  "Memoir",
  "Poetry",
  "Self-Help",
  "True Crime",
  "Business",
];

module.exports = genre;
